import React from "react";
import ReactMarkdown from "react-markdown";
import { User } from "lucide-react";
import { LucyLogo } from "@/components/branding/LucyLogo";

interface ChatMessageProps {
  message: {
    role: "user" | "assistant";
    content?: string;
    type?: string;
    imageUrl?: string;
    created_at: string;
  };
  isStreaming?: boolean;
}

export function ChatMessage({ message, isStreaming }: ChatMessageProps) {
  const isUser = message.role === "user";

  /* ================= IMAGE ARTIFACT ================= */
  if (!isUser && message.type === "image" && message.imageUrl) {
    return (
      <div className="flex gap-3 my-6">
        <LucyLogo size="sm" showGlow />

        <div className="bg-card/70 backdrop-blur-sm rounded-2xl p-4 shadow-[0_0_25px_rgba(168,85,247,0.2)] max-w-xl">
          <img
            src={message.imageUrl}
            alt="Lucy generated image"
            className="rounded-xl w-full mb-3"
            loading="lazy"
          />
          <p className="text-xs text-muted-foreground">
            Generated by Lucy ✨
          </p>
        </div>
      </div>
    );
  }

  /* ================= TEXT MESSAGE ================= */
  return (
    <div
      className={`flex gap-3 my-4 ${
        isUser ? "justify-end" : "justify-start"
      }`}
    >
      {!isUser && <LucyLogo size="sm" showGlow />}

      <div
        className={`rounded-2xl px-5 py-3 max-w-[75%] whitespace-pre-wrap break-words ${
          isUser
            ? "bg-primary text-primary-foreground shadow-md"
            : "bg-card/80 backdrop-blur-sm shadow-[0_0_15px_rgba(168,85,247,0.15)]"
        }`}
      >
        <ReactMarkdown>
          {message.content || ""}
        </ReactMarkdown>

        {isStreaming && (
          <span className="inline-block w-2 h-4 ml-1 animate-pulse bg-primary/80 rounded-sm align-middle" />
        )}
      </div>

      {isUser && (
        <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center">
          <User className="w-4 h-4" />
        </div>
      )}
    </div>
  );
}
