// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// The Lucy Lounge Supabase Configuration
// These are PUBLIC keys - safe to include in client-side code
// PRODUCTION: Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in environment
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://guqljelishrthxiftedq.supabase.co';
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1cWxqZWxpc2hydGh4aWZ0ZWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5ODY1OTEsImV4cCI6MjA3ODU2MjU5MX0.eWFoSl6lgwgO9Hp1OMlP6rnSS1x_8W0jvoiSPvoD3Rs';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});